export const COMPONENT_MANIFEST_VERSION = '1.0.0';

export const COMPONENT_SLOTS = [
  { label: 'Main content', value: 'main' },
  { label: 'Before content', value: 'before-content' },
  { label: 'After content', value: 'after-content' },
  { label: 'Related content', value: 'related-content' },
];

const sharedAccessibility = [
  'Use semantic headings in document order.',
  'Preserve visible keyboard focus.',
  'Do not communicate state by colour alone.',
];

export const COMPONENTS = [
  {
    collection: 'block_hero',
    label: 'Hero',
    description: 'Page openings with imagery and up to two calls to action.',
    status: 'approved',
    version: '1.0.0',
    renderer: 'HeroBlock',
    icon: 'panorama',
    displayTemplate: '{{title}}',
    variants: ['split', 'cover', 'minimal'],
    slots: COMPONENT_SLOTS.map(({ value }) => value),
    fields: ['variant', 'eyebrow', 'title', 'dek', 'image', 'image_alt', 'primary CTA', 'secondary CTA'],
    accessibility: [...sharedAccessibility, 'Provide alternative text for meaningful imagery.'],
    limits: { actions: 2 },
    directusFields: [
      { name: 'variant', type: 'string', default: 'split', choices: [['Split', 'split'], ['Cover', 'cover'], ['Minimal', 'minimal']], note: 'Controlled layout. Split preserves the original layout.' },
      { name: 'image', type: 'uuid' },
      { name: 'image_alt', type: 'string' },
      { name: 'cta_label', type: 'string' },
      { name: 'cta_href', type: 'string' },
      { name: 'secondary_cta_label', type: 'string' },
      { name: 'secondary_cta_href', type: 'string' },
    ],
  },
  {
    collection: 'block_text',
    label: 'Text',
    description: 'Editorial copy, principles, notes, and compact structured content.',
    status: 'approved',
    version: '1.0.0',
    renderer: 'TextBlock',
    icon: 'notes',
    displayTemplate: '{{title}}',
    variants: ['left', 'centered', 'two-column'],
    slots: COMPONENT_SLOTS.map(({ value }) => value),
    fields: ['variant', 'eyebrow', 'title', 'dek', 'body'],
    accessibility: sharedAccessibility,
    limits: { bodyItems: 24 },
    directusFields: [
      { name: 'variant', type: 'string', default: 'two-column', choices: [['Left', 'left'], ['Centred', 'centered'], ['Two column', 'two-column']], note: 'Controlled editorial layout. Two column preserves the original layout.' },
      { name: 'body', type: 'json' },
      { name: 'alignment', type: 'string' },
    ],
  },
  {
    collection: 'block_media',
    label: 'Media',
    description: 'A primary image or lightweight gallery with accessible captions.',
    status: 'approved',
    version: '1.0.0',
    renderer: 'MediaBlock',
    icon: 'image',
    displayTemplate: '{{title}}',
    variants: ['full-width', 'figure', 'gallery'],
    slots: COMPONENT_SLOTS.map(({ value }) => value),
    fields: ['variant', 'eyebrow', 'title', 'dek', 'image', 'image_alt', 'images', 'caption'],
    accessibility: [...sharedAccessibility, 'Provide alternative text for every meaningful image.'],
    limits: { images: 12 },
    directusFields: [
      { name: 'variant', type: 'string', default: 'figure', choices: [['Full-width image', 'full-width'], ['Figure', 'figure'], ['Gallery', 'gallery']], note: 'Controlled media layout. Figure preserves the original layout.' },
      { name: 'image', type: 'uuid' },
      { name: 'image_alt', type: 'string' },
      { name: 'images', type: 'json' },
      { name: 'caption', type: 'text' },
    ],
  },
  {
    collection: 'block_quote',
    label: 'Quote',
    description: 'A pull quote with optional context and attribution.',
    status: 'approved',
    version: '1.0.0',
    renderer: 'QuoteBlock',
    icon: 'format_quote',
    displayTemplate: '{{quote}}',
    variants: [],
    slots: COMPONENT_SLOTS.map(({ value }) => value),
    fields: ['eyebrow', 'title', 'dek', 'quote', 'quote_attribution'],
    accessibility: sharedAccessibility,
    limits: { quoteCharacters: 500 },
    directusFields: [
      { name: 'quote', type: 'text', required: true },
      { name: 'quote_attribution', type: 'string' },
    ],
  },
  {
    collection: 'block_listing',
    label: 'Listing',
    description: 'Filtered cards sourced from products, makers, episodes, or posts.',
    status: 'approved',
    version: '1.0.0',
    renderer: 'ListingBlock',
    icon: 'view_list',
    displayTemplate: '{{listing_type}} - {{title}}',
    variants: ['grid', 'featured', 'archive'],
    slots: COMPONENT_SLOTS.map(({ value }) => value),
    fields: ['variant', 'eyebrow', 'title', 'dek', 'listing_type', 'craft', 'maker', 'items_limit'],
    accessibility: sharedAccessibility,
    limits: { items: 24 },
    directusFields: [
      { name: 'variant', type: 'string', default: 'grid', choices: [['Grid', 'grid'], ['Featured', 'featured'], ['Archive rows', 'archive']], note: 'Controlled listing layout. Grid preserves the original layout.' },
      { name: 'listing_type', type: 'string', required: true },
      { name: 'craft', type: 'string' },
      { name: 'maker', type: 'string' },
      { name: 'items_limit', type: 'integer' },
    ],
  },
  {
    collection: 'block_cta',
    label: 'Call to action',
    description: 'A focused closing prompt with primary and secondary actions.',
    status: 'approved',
    version: '1.0.0',
    renderer: 'CtaBlock',
    icon: 'ads_click',
    displayTemplate: '{{title}}',
    variants: ['panel', 'band'],
    slots: COMPONENT_SLOTS.map(({ value }) => value),
    fields: ['variant', 'eyebrow', 'title', 'dek', 'primary CTA', 'secondary CTA'],
    accessibility: sharedAccessibility,
    limits: { actions: 2 },
    directusFields: [
      { name: 'variant', type: 'string', default: 'panel', choices: [['Panel', 'panel'], ['Full-width band', 'band']], note: 'Controlled call-to-action layout. Panel preserves the original layout.' },
      { name: 'cta_label', type: 'string' },
      { name: 'cta_href', type: 'string' },
      { name: 'secondary_cta_label', type: 'string' },
      { name: 'secondary_cta_href', type: 'string' },
    ],
  },
  {
    collection: 'block_slideshow',
    label: 'Slideshow',
    description: 'An accessible, editorial sequence of credited images.',
    status: 'approved',
    version: '1.0.0',
    renderer: 'SlideshowBlock',
    primitives: ['shadcn:carousel', 'shadcn:button'],
    icon: 'view_carousel',
    displayTemplate: '{{title}}',
    variants: ['editorial', 'full-width', 'thumbnail-rail'],
    slots: ['main', 'before-content', 'after-content'],
    fields: ['variant', 'eyebrow', 'title', 'dek', 'slides', 'show_captions', 'show_counter', 'autoplay', 'interval'],
    accessibility: [
      ...sharedAccessibility,
      'Every meaningful slide requires alternative text.',
      'Support previous and next keyboard navigation.',
      'Autoplay must provide a pause control and respect reduced motion.',
    ],
    limits: { slides: 12, minimumIntervalMs: 4000 },
    directusFields: [
      { name: 'variant', type: 'string', default: 'editorial', choices: [['Editorial', 'editorial'], ['Full width', 'full-width'], ['Thumbnail rail', 'thumbnail-rail']], note: 'Controlled slideshow layout.' },
      {
        name: 'slides',
        type: 'json',
        required: true,
        interface: 'list',
        note: 'Maximum 12 slides. Alternative text is required for meaningful images.',
        listFields: [
          { field: 'image', name: 'Image', type: 'uuid', interface: 'file-image', required: true },
          { field: 'image_alt', name: 'Alternative text', type: 'string', interface: 'input', required: true },
          { field: 'caption', name: 'Caption', type: 'text', interface: 'input-multiline' },
          { field: 'credit', name: 'Credit', type: 'string', interface: 'input' },
        ],
      },
      { name: 'show_captions', type: 'boolean', default: true },
      { name: 'show_counter', type: 'boolean', default: true },
      { name: 'autoplay', type: 'boolean', default: false, note: 'Disabled for visitors who prefer reduced motion.' },
      { name: 'interval', type: 'integer', default: 6000, note: 'Minimum 4000 milliseconds.' },
    ],
  },
  {
    collection: 'block_podcast_player',
    label: 'Podcast player',
    description: 'A branded, accessible episode player connected to Hugh McNeill podcast audio, transcripts, maker pages, and related objects.',
    status: 'approved',
    version: '1.0.0',
    renderer: 'PodcastPlayerBlock',
    primitives: ['shadcn:button'],
    trustedOpenSource: [
      {
        package: 'media-chrome',
        source: 'github:muxinc/media-chrome',
        license: 'MIT',
        purpose: 'Accessible native media controls for podcast audio playback.',
        allowedFor: ['audio-playback', 'podcast-player'],
      },
    ],
    icon: 'podcasts',
    displayTemplate: '{{episode_title}}',
    variants: ['feature', 'compact', 'sticky-bar'],
    slots: COMPONENT_SLOTS.map(({ value }) => value),
    fields: ['variant', 'eyebrow', 'title', 'dek', 'episode', 'episode_title', 'guest', 'audio_url', 'poster_image', 'duration', 'published_date', 'transcript', 'apple_url', 'spotify_url', 'podbean_url', 'related_maker', 'related_products'],
    accessibility: [
      ...sharedAccessibility,
      'Use native audio semantics and labelled controls.',
      'All play, pause, seek, mute, transcript, and external-link controls must be keyboard operable.',
      'Do not autoplay audio.',
      'Provide a text transcript or transcript link where available.',
    ],
    limits: {
      actions: 4,
      relatedProducts: 6,
      autoplay: false,
      cmsExecutableContent: false,
    },
    directusFields: [
      { name: 'variant', type: 'string', default: 'feature', choices: [['Feature', 'feature'], ['Compact', 'compact'], ['Sticky bar', 'sticky-bar']], note: 'Controlled podcast player layout.' },
      { name: 'episode', type: 'string', required: true, note: 'Episode slug, number, or relation key.' },
      { name: 'episode_title', type: 'string', required: true },
      { name: 'guest', type: 'string' },
      { name: 'audio_url', type: 'string', required: true, note: 'Direct MP3/audio URL from RSS or Directus file. No embed JavaScript.' },
      { name: 'poster_image', type: 'uuid' },
      { name: 'duration', type: 'string' },
      { name: 'published_date', type: 'string' },
      { name: 'transcript', type: 'text' },
      { name: 'apple_url', type: 'string' },
      { name: 'spotify_url', type: 'string' },
      { name: 'podbean_url', type: 'string' },
      { name: 'related_maker', type: 'string' },
      { name: 'related_products', type: 'json', note: 'Array of product slugs. Maximum 6.' },
    ],
  },
];

export const APPROVED_COMPONENTS = COMPONENTS.filter(({ status }) => status === 'approved');
export const APPROVED_COMPONENT_COLLECTIONS = APPROVED_COMPONENTS.map(({ collection }) => collection);

export function componentByCollection(collection) {
  return COMPONENTS.find((component) => component.collection === collection);
}
